version: 2
jobs:
  build:
    docker:
      - image: circleci/clojure:openjdk-11-lein-2.8.3

    working_directory: ~/repo

    environment:
      LEIN_ROOT: "true"

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "project.clj" }}
            - v1-dependencies-

      - run: lein with-profile +kaocha deps

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "project.clj" }}

      - run: lein kaocha
